name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build CML Extensible Engine with Hail v0.2 Support
      run: docker build . --file Dockerfile --tag rjbenikar/cdhcdswsengine:new
    - name: Perform DH Login
      run: docker login -u ${{ secrets.UID }} -p ${{ secrets.PASSWORD }}
    - name: Push New Image
      run: docker push rjbenikar/cdhcdswsengine:new
